; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.41"

projects[kw_manifests][type] = "module"
projects[kw_manifests][download][type] = "git"
projects[kw_manifests][download][url] = "git://github.com/kraftwagen/kw-manifests.git"
projects[kw_manifests][subdir] = "kraftwagen"

projects[kw_itemnames][type] = "module"
projects[kw_itemnames][download][type] = "git"
projects[kw_itemnames][download][url] = "git://github.com/kraftwagen/kw-itemnames.git"
projects[kw_itemnames][subdir] = "kraftwagen"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9"

projects[datepicker][subdir] = "contrib"
projects[datepicker][version] = "1.0"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[features][subdir] = "contrib"
projects[features][version] = "2.7"

projects[fieldable_panels_panes][subdir] = "contrib"
projects[fieldable_panels_panes][version] = "1.7"

projects[gmap][subdir] = "contrib"
projects[gmap][version] = "2.10"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.5"

projects[location][subdir] = "contrib"
projects[location][version] = "3.7"

projects[menu_attributes][subdir] = "contrib"
projects[menu_attributes][version] = "1.0-rc3"

projects[menu_item_visibility][subdir] = "contrib"
projects[menu_item_visibility][version] = "1.0-beta1"

projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.8"

projects[panelizer][subdir] = "contrib"
projects[panelizer][version] = "3.1"

projects[registration][subdir] = "contrib"
projects[registration][version] = "1.6"

projects[search_krumo][subdir] = "contrib"
projects[search_krumo][version] = "1.6"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.13"

; Themes
projects[omega][version] = "4.4"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tests][download][type] = ""
projects[tests][download][url] = ""
projects[tests][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[psr_0_test][download][type] = ""
projects[psr_0_test][download][url] = ""
projects[psr_0_test][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[psr_4_test][download][type] = ""
projects[psr_4_test][download][url] = ""
projects[psr_4_test][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[travel_agency_custom_content_types][download][type] = ""
projects[travel_agency_custom_content_types][download][url] = ""
projects[travel_agency_custom_content_types][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[travel_agency_custom_panes][download][type] = ""
projects[travel_agency_custom_panes][download][url] = ""
projects[travel_agency_custom_panes][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[travel_agency_globals][download][type] = ""
projects[travel_agency_globals][download][url] = ""
projects[travel_agency_globals][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[travel_agency_menus][download][type] = ""
projects[travel_agency_menus][download][url] = ""
projects[travel_agency_menus][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[travel_agency_modules][download][type] = ""
projects[travel_agency_modules][download][url] = ""
projects[travel_agency_modules][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[travel_agency_structures][download][type] = ""
projects[travel_agency_structures][download][url] = ""
projects[travel_agency_structures][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[travel_agency_views][download][type] = ""
projects[travel_agency_views][download][url] = ""
projects[travel_agency_views][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[travel_agency][download][type] = ""
projects[travel_agency][download][url] = ""
projects[travel_agency][type] = "theme"

